#
# Makefile for aura sync drivers.
#
obj-y		+= ene_8k41.o
obj-$(CONFIG_AURA_SYNC_INBOX)	+= ene_8k41_inbox.o
#obj-$(CONFIG_AURA_SYNC_STATION)	+= ene_8k41_station.o
obj-$(CONFIG_AURA_SYNC_POGO)	+= ene_8k41_pogo.o

